name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v3
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '="/"'
          replace: '="/yot/"'
          include: "index.html"
